spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.35.81:5432/postgres
    username: postgres
    password: tes1234
  jpa:
    generate-ddl: false
    show-sql: true